lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima
title: Dan Drennan
description: Statistics, ML, and reproducible software

collections:
  posts:
    output: true
    permalink: /:collection/:title/

exclude:
  - drafts
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - README.md
