version: '3'
services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    command: >
      sh -c "bundle install &&
      bundle exec jekyll serve --watch --force_polling --livereload --host 0.0.0.0"
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - jekyll_bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
volumes:
  jekyll_bundle:
